### ISSUE TITLE
data directory

### ISSUE THREAD

**Issue by jeongheo97** [mac4n6/APOLLO#18]
I am trying to use APOLLO and I am stuck on one part. I am trying to export my screentime from my iPhone and make it into a CSV file to run it on automl. But I am totally lost on what to put on the data directory.
I am currently on this step on Linux.
apollo.py -o {csv} -p {apple} -v {10.15} -k /Users/heojeong/Downloads/apollo/APOLLO/modules <data directory>
I connected my iPhone to my mac to check on the directory but I cannot find the directory path....and I am not even sure if that is how I should do!
Can you please help me? thank you so much

**Comment by tobynoe** [comment]
You have to have full access over your iPhone in order to use this script. The `data_dir_to_analyze` has to be an extracted database or physical image of your device (see `-h`). Both methods require a Jailbroken device or other kinds of extractions. Otherwise, the databases can't be accessed. So only connecting your iPhone to your Mac doesn't work.

**Comment by mac4n6** [comment]
In addition, when running apollo.py the arguments to not need the curly brackets.
